PREFIX=.
INCLUDE_DIR=$(PREFIX)/include
SRC_DIR=$(PREFIX)/src

K=2

CC=gcc
CFLAGS= -c -std=c99 -Wall -Werror -DK=$(K)
CPPFLAGS= -I$(INCLUDE_DIR) -D_GNU_SOURCE
LDFLAGS= -lm

ifeq ($(DEBUG),yes)
	CFLAGS+= -g -DDEBUG_MODE
else
	CFLAGS+= -O2
endif

SIMULATED_ANNEALING_T_0=1000
SIMULATED_ANNEALING_NB_FAIL_MAX=10
SIMULATED_ANNEALING_ACCEPTATION_PROBA=100
SIMULATED_ANNEALING_T_MIN=0.1
SIMULATED_ANNEALING_RATIO=0.9
TABOO_SIZE=10
TABOO_ITERMAX=100
GRAD_OPTIM='DESC_SEED(v)=(v/10.)'

CFLAGS+= -DSIMULATED_ANNEALING_T_0=$(SIMULATED_ANNEALING_T_0) \
	 -DSIMULATED_ANNEALING_NB_FAIL_MAX=$(SIMULATED_ANNEALING_NB_FAIL_MAX) \
	 -DSIMULATED_ANNEALING_ACCEPTATION_PROBA=$(SIMULATED_ANNEALING_ACCEPTATION_PROBA) \
	 -DSIMULATED_ANNEALING_T_MIN=$(SIMULATED_ANNEALING_T_MIN) \
	 -DSIMULATED_ANNEALING_RATIO=$(SIMULATED_ANNEALING_RATIO) \
	 -DTABOO_SIZE=$(TABOO_SIZE) \
	 -DTABOO_ITERMAX=$(TABOO_ITERMAX) \
	 -D$(GRAD_OPTIM)

ifeq ($(RANDOM_ANNEALING),yes)
	CFLAGS+= -DSIMULATED_ANNEALING_RANDOM_ACCEPTATION
endif

SRC=$(wildcard $(SRC_DIR)/*.c)
OBJS=$(SRC:%.c=%.o)

OUT=partition

.PHONY: clean all mrproper

.PRECIOUS: %.d

all: $(OUT)

$(OUT): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) -o $@ $(CFLAGS) $(CPPFLAGS) $^

clean:
	$(RM) $(OBJS)
	find -name "*~" -delete

mrproper: clean
	$(RM) $(OUT)
	find -name "*.d" -delete

include $(SRC:.c=.d)

%.d: %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MM $^ > $@
